local status = require("status")
print("Initial status:", status.getTicks(), status.getName())
status.setTicks(42)
status.setName("New status")
assert(status.getTicks() == 42 and status.getName() == "New status")
print("Updated status:", status.getTicks(), status.getName())
